[project]
name = "yaka"
version = "0.1.0"
description = "An application to test how to build on konflux"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=44.0.0",
]

[dependency-groups]
dev = [
    "pybuild-deps>=0.4.0",
]
